#!/bin/bash

default_frequency=100
default_mode=study
default_harmonics=5

declare -A modes
modes["alert"]="24 32"
modes["study"]="16 24"
modes["relax"]="12 16"
modes["creative"]="6 16"
modes["sleep"]="1 2"


# display help
if [[ $1 = "-h" ]]; then
    echo -e -n "use: binaural ["
    echo -e -n "${!modes[@]}"
    echo -e -n "] [basefrequency] [harmonics_number] ."
    echo -e -n "\t\tDefaults to: binaural $default_mode $default_frequency $default_harmonics"
    exit 0
fi

# parse mode
if [[ ! -v modes[$1] && -n $1 ]]; then
    echo -e "$1 is not a valid mode. Use parameter -h to have more information."
    exit -1
    elif [[ -z $1 ]]; then
    mode=$default_mode
else
    mode=$1
fi;

# parse base frequency
if [[ -z $2 ]]; then
    frequency=$default_frequency
    elif [[ $2 =~ ^[0-9]+$ ]]; then
    frequency=$2
else
    echo "provide a valid base frequency (in HZ)"
    exit -2
fi

# parse harmonics number
if [[ -z $3 ]]; then
    harmonics=$default_harmonics
    elif [[ $3 =~ ^[0-9]+$ ]]; then
    harmonics=$3
else
    echo "provide a valid harmonics number"
    exit -3
fi

# get the frequencies delta
[[ ${modes[$mode]} =~ ^[0-9]+ ]] && df0=${BASH_REMATCH[0]}
[[ ${modes[$mode]} =~ [0-9]+$ ]] && df1=${BASH_REMATCH[0]}

# create the command
command="play -q -n synth sine $(expr $frequency) remix 1 1"
for ((i=0; i<$harmonics; i++)); do
    harmonic_f=$((($i+2)**2))
    command="$command synth sine $(($frequency + $df0 + $harmonic_f)) remix 1 0 \
    synth sine $(($frequency + $df1 + $harmonic_f)) remix 0 1"
done
command="$command remix -"

# tell the user some stats
echo -e "Playing mode $mode, base frequency $frequency Hz, \
tones at $(expr $frequency + $df0) Hz and $(expr $frequency + $df1) Hz, \
$harmonics harmonics"

# play the command
eval $command