#!/bin/bash

# get help in order to know the usage of the script
if [[ $1 = "-h" || $# = 0 ]]; then
    echo "Usage: randomfile [file path] [number of rows] [number of columns]"
    exit 0
fi

# load file path from arguments
if [[ -z $1 ]]; then
    echo "No file path given"
    exit 1
    elif [[ ! -f $1 ]]; then
    echo "File path is not a file"
    exit 1
fi

# load text width from arguments
if [[ -z $2 ]]; then
    cols=80
    echo "No text width given, defaulting to $cols"
    elif [[ ! $2 =~ ^[0-9]+$ ]]; then
    echo "Text width is not a number"
    exit 1
else
    cols=$2
fi
# load text height from arguments
if [[ -z $3 ]]; then
    rows=40
    echo "No text height given, defaulting to $rows"
    elif [[ ! $3 =~ ^[0-9]+$ ]]; then
    echo "Text height is not a number"
    exit 1
else
    rows=$3
fi


# write the file
for ((i=0; i<$rows; i++)); do
    for ((j=0; j<$cols; j++)); do
        val=$((33 + RANDOM % 93))
        printf \\$(printf '%03o' $val)
    done
    echo
done > $1